# SPDX-FileCopyrightText: 2025 Sébastien Helleu <flashcode@flashtux.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1

[[annotations]]
path = [
    "debian-devel/**",
    "debian-stable/**",
    "icons/**/*.png",
    "icons/**/*.svg",
    "src/plugins/php/weechat-php_arginfo.h",
    "src/plugins/php/weechat-php_legacy_arginfo.h",
    "tools/debian/patches/**",
    "weechat.desktop",
    "weechat.pc.in",
]
precedence = "override"
SPDX-FileCopyrightText = "2003-2025 Sébastien Helleu <flashcode@flashtux.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
