# SPDX-FileCopyrightText: 2003-2025 Sébastien Helleu <flashcode@flashtux.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

version = 1

[[annotations]]
path = [
    ".editorconfig",
    ".gitattributes",
    ".github/**",
    ".gitignore",
    ".mailmap",
    "AUTHORS.md",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "README.md",
    "UPGRADING.md",
    "config.h.cmake",
    "debian-*/**",
    "icons/**",
    "src/plugins/php/weechat-php_arginfo.h",
    "src/plugins/php/weechat-php_legacy_arginfo.h",
    "tools/debian/patches/**",
    "weechat.desktop",
    "weechat.pc.in",
]
SPDX-FileCopyrightText = "2018-2025 Sébastien Helleu <flashcode@flashtux.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
